// Тексты чат-бота MAX на трёх языках. Сроки и требования в бот не пишутся вручную:
// чек-лист «После приезда» собирается из data/rules.json, ссылки — из data/sources.json.

export const BOT_LANGS = ['ru', 'en', 'zh'];

export const MENU_ACTIONS = ['open', 'route', 'arrival', 'changes', 'sources', 'lang', 'about'];

export const texts = {
  ru: {
    menu: {
      open: '🚀 Открыть СтудМаршрут',
      route: '🧭 Мой маршрут',
      arrival: '📋 После приезда',
      changes: '⚡ Изменились обстоятельства',
      sources: '🔗 Официальные источники',
      lang: '🌐 Язык',
      about: 'ℹ️ О проекте',
    },
    backToMenu: '☰ Меню',
    openSource: '🔗 Открыть официальный источник',
    buildRoute: '🚀 Построить мой маршрут',
    calcDates: '🚀 Рассчитать мои даты',
    addEvent: '🚀 Добавить событие в маршрут',
    github: 'GitHub проекта',
    welcome: [
      '👋 **СтудМаршрут**',
      '',
      'Помогаю иностранному студенту СПбГЭУ в первые недели после приезда: что сделать, к какому сроку, куда обратиться и где официальный источник.',
      '',
      'Нажмите **«🚀 Открыть СтудМаршрут»**, чтобы собрать персональный маршрут, или выберите раздел ниже.',
      '',
      '_Информационный помощник, а не официальный сервис ведомства._',
    ],
    menuTitle: 'Выберите раздел:',
    open: 'Откройте mini-app кнопкой ниже: там строится персональный маршрут с датами, прогрессом и источниками.',
    route: [
      '🧭 **Мой маршрут**',
      '',
      'Маршрут строится в mini-app за 1–2 минуты. Понадобятся только:',
      '• дата въезда в Россию;',
      '• где вы живёте: общежитие СПбГЭУ или частный адрес;',
      '• планируете ли быть в России дольше 90 дней;',
      '• нужна ли виза и до какой даты она действует;',
      '• до какой даты действует миграционный учёт, если он уже оформлен.',
      '',
      'Вы получите список шагов со статусами «Срочно», «Скоро», «Без установленного срока», ближайшее действие и прогресс. Отметки о выполнении хранятся только на вашем устройстве.',
      '',
      'Паспортные данные, ФИО и фото документов не запрашиваются.',
    ],
    arrivalTitle: '📋 **После приезда: первые шаги**',
    arrivalLead: 'Порядок для иностранного студента СПбГЭУ. Срок указан, только если его называет официальный источник.',
    arrivalHousing: {
      dorm_registration: 'общежитие',
      private_registration: 'частный адрес',
    },
    arrivalConditions: {
      fingerprint_medical: 'при обучении дольше 90 дней; кроме граждан Беларуси',
      visa_extension: 'если нужна виза',
      registration_extension: 'после оформления учёта',
    },
    arrivalFooter: 'Точные даты под вашу ситуацию рассчитает mini-app.',
    changes: [
      '⚡ **Изменились обстоятельства**',
      '',
      'СПбГЭУ просит обратиться в отдел виз и регистраций **в течение 1 рабочего дня**, если вы:',
      '• пересекли границу (новый въезд);',
      '• жили в гостинице или лежали в больнице;',
      '• переехали;',
      '• получили новый паспорт.',
      '',
      'В mini-app откройте раздел «Изменения», укажите событие и дату: маршрут добавит задачу с рассчитанным сроком.',
    ],
    sourcesTitle: '🔗 **Официальные источники**',
    sourcesLead: 'Каждое правило СтудМаршрута привязано к первоисточнику. Если на официальной странице указано иное, следуйте официальной странице.',
    checked: 'проверено',
    langTitle: '🌐 Выберите язык / Choose language / 选择语言',
    langSet: '✅ Язык бота: русский.',
    about: [
      'ℹ️ **О проекте**',
      '',
      '**СтудМаршрут** — чат-бот и mini-app в MAX от команды **MAXimum Care** (трек «Забота о людях»).',
      'Команда: Дмитриева Екатерина, Мыкало Валерия, Смирнова Екатерина.',
      '',
      'Для кого: иностранный студент 18+, впервые приехавший на очное обучение в СПбГЭУ.',
      'Что делает: собирает правила университета и портала госуслуг Санкт-Петербурга в один персональный маршрут со сроками и источниками.',
      '',
      '• Не является официальным сервисом и не заменяет решение ведомства.',
      '• Интеграций с МВД и Госуслугами нет: используются заранее проверенные правила.',
      '• Паспортные данные, ФИО и документы не собираются.',
    ],
    help: [
      '**Как пользоваться**',
      'Нажимайте кнопки меню: команды вводить не обязательно.',
      '',
      'Команды: /start — начало, /menu — меню, /sources — источники, /demo — сценарий проверки, /help — помощь, /ru, /en, /zh — язык.',
    ],
    demo: [
      '**Проверка за 1 минуту**',
      '1. Нажмите «🚀 Открыть СтудМаршрут».',
      '2. Нажмите «Пример для проверки» или заполните анкету: общежитие, дольше 90 дней, нужна виза.',
      '3. Нажмите «Построить маршрут»: появятся прогресс, ближайшее действие и ближайший срок.',
      '4. Откройте карточку, нажмите «Открыть официальный источник», затем «Отметить выполненным».',
      '5. В разделе «Изменения» выберите событие и дату: маршрут добавит срочную задачу.',
      '6. Переключите язык: RU / EN / 中文.',
    ],
    unknown: 'Я работаю через кнопки меню. Выберите раздел ниже или нажмите «🚀 Открыть СтудМаршрут».',
  },
  en: {
    menu: {
      open: '🚀 Open StudRoute',
      route: '🧭 My route',
      arrival: '📋 After arrival',
      changes: '⚡ Circumstances changed',
      sources: '🔗 Official sources',
      lang: '🌐 Language',
      about: 'ℹ️ About',
    },
    backToMenu: '☰ Menu',
    openSource: '🔗 Open official source',
    buildRoute: '🚀 Build my route',
    calcDates: '🚀 Calculate my dates',
    addEvent: '🚀 Add the event to my route',
    github: 'Project on GitHub',
    welcome: [
      '👋 **StudRoute (СтудМаршрут)**',
      '',
      'I help international students at UNECON (СПбГЭУ) in their first weeks after arrival: what to do, by when, where to go and where the official source is.',
      '',
      'Tap **“🚀 Open StudRoute”** to build your personal route, or choose a section below.',
      '',
      '_An information assistant, not an official government service._',
    ],
    menuTitle: 'Choose a section:',
    open: 'Open the mini app with the button below: it builds your personal route with dates, progress and sources.',
    route: [
      '🧭 **My route**',
      '',
      'The route is built in the mini app in 1–2 minutes. You only need:',
      '• your date of entry to Russia;',
      '• where you live: UNECON dormitory or a private address;',
      '• whether you will stay in Russia for more than 90 days;',
      '• whether you need a visa and when it expires;',
      '• when your migration registration expires, if you already have it.',
      '',
      'You get a list of steps marked “Urgent”, “Soon” or “No set deadline”, your next action and your progress. Completion marks are stored only on your device.',
      '',
      'We never ask for passport details, full name or photos of documents.',
    ],
    arrivalTitle: '📋 **After arrival: first steps**',
    arrivalLead: 'The order for an international student at UNECON. A deadline is shown only if the official source states it.',
    arrivalHousing: {
      dorm_registration: 'dormitory',
      private_registration: 'private address',
    },
    arrivalConditions: {
      fingerprint_medical: 'for studies longer than 90 days; not for citizens of Belarus',
      visa_extension: 'if you need a visa',
      registration_extension: 'once you are registered',
    },
    arrivalFooter: 'The mini app calculates the exact dates for your situation.',
    changes: [
      '⚡ **Circumstances changed**',
      '',
      'UNECON asks you to contact the Visa and Registration Office **within 1 working day** if you:',
      '• crossed the border (new entry);',
      '• stayed in a hotel or a hospital;',
      '• moved to a new address;',
      '• received a new passport.',
      '',
      'In the mini app, open “Changes”, choose the event and its date: the route adds a task with a calculated deadline.',
    ],
    sourcesTitle: '🔗 **Official sources**',
    sourcesLead: 'Every StudRoute rule is linked to its primary source. If the official page says otherwise, follow the official page.',
    checked: 'checked',
    langTitle: '🌐 Выберите язык / Choose language / 选择语言',
    langSet: '✅ Bot language: English.',
    about: [
      'ℹ️ **About**',
      '',
      '**StudRoute (СтудМаршрут)** is a chatbot and mini app in MAX by the **MAXimum Care** team (track “Care for People”).',
      'Team: Ekaterina Dmitrieva, Valeria Mykalo, Ekaterina Smirnova.',
      '',
      'For: an 18+ international student arriving at UNECON (СПбГЭУ) for full-time study for the first time.',
      'What it does: combines university rules and the Saint Petersburg public services portal into one personal route with deadlines and sources.',
      '',
      '• It is not an official service and does not replace an agency decision.',
      '• There is no integration with the Ministry of Internal Affairs (МВД) or Gosuslugi (Госуслуги): pre-verified rules are used.',
      '• No passport data, full names or documents are collected.',
    ],
    help: [
      '**How to use**',
      'Use the menu buttons: you do not have to type commands.',
      '',
      'Commands: /start — start, /menu — menu, /sources — sources, /demo — test scenario, /help — help, /ru, /en, /zh — language.',
    ],
    demo: [
      '**1-minute check**',
      '1. Tap “🚀 Open StudRoute”.',
      '2. Tap “Try an example” or fill in the form: dormitory, more than 90 days, visa required.',
      '3. Tap “Build route”: you will see progress, the next action and the nearest deadline.',
      '4. Open a card, tap “Open official source”, then “Mark as done”.',
      '5. In “Changes”, choose an event and a date: the route adds an urgent task.',
      '6. Switch the language: RU / EN / 中文.',
    ],
    unknown: 'I work through the menu buttons. Choose a section below or tap “🚀 Open StudRoute”.',
  },
  zh: {
    menu: {
      open: '🚀 打开 СтудМаршрут',
      route: '🧭 我的路线',
      arrival: '📋 抵达后',
      changes: '⚡ 情况有变化',
      sources: '🔗 官方来源',
      lang: '🌐 语言',
      about: 'ℹ️ 关于项目',
    },
    backToMenu: '☰ 菜单',
    openSource: '🔗 打开官方来源',
    buildRoute: '🚀 生成我的路线',
    calcDates: '🚀 计算我的日期',
    addEvent: '🚀 将事件加入路线',
    github: '项目 GitHub',
    welcome: [
      '👋 **学生路线（СтудМаршрут）**',
      '',
      '帮助СПбГЭУ国际学生度过抵达后的最初几周：要办什么、什么时候办、去哪里办，以及官方来源在哪里。',
      '',
      '点击 **“🚀 打开 СтудМаршрут”** 生成个人路线，或在下方选择栏目。',
      '',
      '_这是信息助手，不是政府部门的官方服务。_',
    ],
    menuTitle: '请选择栏目：',
    open: '点击下方按钮打开小程序：在那里生成带日期、进度和来源的个人路线。',
    route: [
      '🧭 **我的路线**',
      '',
      '在小程序中1–2分钟即可生成路线，只需要：',
      '• 入境俄罗斯的日期；',
      '• 居住地点：СПбГЭУ学生宿舍或校外私人住址；',
      '• 是否计划在俄罗斯停留超过90天；',
      '• 是否需要签证以及签证有效期；',
      '• 如已办理移民登记（Миграционный учёт），其有效期。',
      '',
      '您将看到标有“紧急”“即将到期”“无规定期限”的步骤清单、下一步行动和完成进度。完成标记只保存在您的设备上。',
      '',
      '我们不收集护照信息、姓名或证件照片。',
    ],
    arrivalTitle: '📋 **抵达后：最初几步**',
    arrivalLead: 'СПбГЭУ国际学生的办理顺序。只有官方来源明确规定时才显示期限。',
    arrivalHousing: {
      dorm_registration: '学生宿舍',
      private_registration: '私人住址',
    },
    arrivalConditions: {
      fingerprint_medical: '学习超过90天时；白俄罗斯公民除外',
      visa_extension: '如需签证',
      registration_extension: '办理登记后',
    },
    arrivalFooter: '小程序会根据您的情况计算具体日期。',
    changes: [
      '⚡ **情况有变化**',
      '',
      '如果您有以下情况，СПбГЭУ要求您 **在1个工作日内** 联系签证与登记部门（отдел виз и регистраций）：',
      '• 出入境（重新入境）；',
      '• 入住酒店或住院；',
      '• 搬家；',
      '• 换发新护照。',
      '',
      '在小程序中打开“变更”，选择事件和日期：路线会添加一项计算好期限的任务。',
    ],
    sourcesTitle: '🔗 **官方来源**',
    sourcesLead: 'СтудМаршрут的每条规则都对应官方原始来源。如官方页面有不同说明，请以官方页面为准。',
    checked: '核验日期',
    langTitle: '🌐 Выберите язык / Choose language / 选择语言',
    langSet: '✅ 机器人语言：中文。',
    about: [
      'ℹ️ **关于项目**',
      '',
      '**学生路线（СтудМаршрут）** 是 **MAXimum Care** 团队（“关爱大众”赛道）在MAX中开发的聊天机器人和小程序。',
      '团队成员：Дмитриева Екатерина、Мыкало Валерия、Смирнова Екатерина。',
      '',
      '面向：18岁以上、首次赴СПбГЭУ就读全日制课程的国际学生。',
      '作用：把大学规定和圣彼得堡政务服务门户的信息整合为一条带期限和来源的个人路线。',
      '',
      '• 不是官方服务，不能替代政府部门的决定。',
      '• 未与俄罗斯内务部（МВД）或“Госуслуги”（俄罗斯国家服务门户）集成，使用预先核验的规则。',
      '• 不收集护照信息、姓名或证件。',
    ],
    help: [
      '**使用方法**',
      '请点击菜单按钮，无需输入命令。',
      '',
      '命令：/start — 开始，/menu — 菜单，/sources — 来源，/demo — 检查流程，/help — 帮助，/ru、/en、/zh — 语言。',
    ],
    demo: [
      '**1分钟检查**',
      '1. 点击“🚀 打开 СтудМаршрут”。',
      '2. 点击“示例数据”或填写问卷：学生宿舍、超过90天、需要签证。',
      '3. 点击“生成办理路线”：将显示进度、下一步行动和最近期限。',
      '4. 打开任务卡片，点击“打开官方来源”，然后点击“标记为已完成”。',
      '5. 在“变更”中选择事件和日期：路线会添加一项紧急任务。',
      '6. 切换语言：RU / EN / 中文。',
    ],
    unknown: '我通过菜单按钮工作。请在下方选择栏目，或点击“🚀 打开 СтудМаршрут”。',
  },
};

export const langButtons = [
  { lang: 'ru', text: 'Русский' },
  { lang: 'en', text: 'English' },
  { lang: 'zh', text: '中文' },
];
